### ISSUE TITLE
improve API error handling

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/json-api-client#36]
PLEASE EDIT THIS INITIAL COMMENT AS YOU SEE FIT

Issue: to handle api errors from json-api-client better.

 ## Before SGL (1st PRs):
1. update json-api-client to return error object (with status and response fields) - PR #37 
2. update panoptes-client to return error object (with status and response fields) - `panoptes-client` PR [#62](https://github.com/zooniverse/panoptes-javascript-client/pull/62)

## If Possible Before SGL (2nd PRs):
1. bump json-api-client superagent version to 1.8.2, use native superagent Promise

## After SGL (other PRs):
1. combine json-api-client and panoptes-javascript-client

**Comment by eatyourgreens** [comment]
Errors should be coming back as simple objects in the response body. http://jsonapi.org/format/#errors I think the Panoptes JavaScript client is swallowing those responses, instead of passing them to the client app.

**Comment by eatyourgreens** [comment]
Related discussion in #27 too.

**Comment by mcbouslog** [comment]
@eatyourgreens - is the `error.response.body.errors` array from the superagent error object (screen shot below) what you mention above or are you referring to what the [jsonapi docs](http://jsonapi.org/format/1.1/#error-objects) note - "Error objects MUST be returned as an array keyed by errors in the top level of a JSON API document?" 
I'm not sure I entire understand what that is stating. Is there an api request I could do to test what multiple errors would look like?

![screen shot 2017-03-14 at 3 25 40 pm](https://cloud.githubusercontent.com/assets/12118751/23920905/86a7e238-08ca-11e7-8d06-455b4377aa6e.png)

**Comment by mcbouslog** [comment]
I'm thinking we replace this issue with separate, more specific issues, as we continue to make improvements to this client and the panoptes-javascript-client.
